
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu May 04 12:14:37 EDT 2017
//----------------------------------------------------

package bantam.parser;

/** CUP generated class containing symbol constants. */
public class TokenIds {
  /* terminals */
  public static final int DIVIDE = 19;
  public static final int SEMI = 39;
  public static final int LPAREN = 33;
  public static final int DECR = 32;
  public static final int INCR = 31;
  public static final int FOR = 8;
  public static final int MINUS = 17;
  public static final int INSTANCEOF = 12;
  public static final int RPAREN = 34;
  public static final int NOT = 21;
  public static final int AND = 22;
  public static final int LT = 26;
  public static final int OR = 23;
  public static final int COMMA = 40;
  public static final int THROW = 15;
  public static final int CLASS = 3;
  public static final int GEQ = 29;
  public static final int PLUS = 16;
  public static final int ASSIGN = 30;
  public static final int IF = 5;
  public static final int LSQBRACE = 37;
  public static final int ID = 42;
  public static final int DOT = 41;
  public static final int EOF = 0;
  public static final int RETURN = 11;
  public static final int INT_CONST = 43;
  public static final int NEW = 10;
  public static final int error = 1;
  public static final int TRY = 13;
  public static final int BREAK = 9;
  public static final int EQ = 24;
  public static final int LEX_ERROR = 2;
  public static final int TIMES = 18;
  public static final int LBRACE = 35;
  public static final int ELSE = 6;
  public static final int WHILE = 7;
  public static final int RBRACE = 36;
  public static final int MODULUS = 20;
  public static final int EXTENDS = 4;
  public static final int NE = 25;
  public static final int LEQ = 27;
  public static final int BOOLEAN_CONST = 44;
  public static final int RSQBRACE = 38;
  public static final int STRING_CONST = 45;
  public static final int GT = 28;
  public static final int CATCH = 14;
}

